Cypress.Commands.add("signIn", (user) => {
  cy.visit("/")
  cy.location("protocol").should("eq", "https:")
  cy.get("#header .header__icon-wrapper .header__icon:first a").click()
  cy.get("form").within(() => {
    cy.get("input[type='email']").type(user.email)
    cy.get("input[type='password']").type(user.password)
    cy.root().submit()
  })
})
Cypress.Commands.add("addAdress", (item) => {
  cy.get(".q-modal-content .q-box .q-input-wrapper:first input[type='text']").click({ force: true }).type(item.title)
  cy.get(".q-modal-content .q-box .grid-input-container .left input[type='text']").click({ force: true }).type(item.name)
  cy.get(".q-modal-content .q-box .grid-input-container .right input[type='text']").click({ force: true }).type(item.surname)
  cy.get(".q-modal-content .q-box input.phone-input").type(item.phone)
  cy.get(".q-modal-content .q-box .grid-input-container .left .dropdown select").select(item.city)
  cy.get(".q-modal-content .q-box .grid-input-container .right .dropdown select").select(item.district)
  cy.get(".q-modal-content .q-box form .dropdown:last select").select(item.neighborhood)
  cy.get(".q-modal-content .q-box .address-text-area ").type(item.fullAdress)
  cy.get(".q-modal-content button").click()
  cy.get(".q-popup-main .address-creation-success").should("exist")
  cy.get(".q-popup-main .address-creation-success button").click()
})